### PR TITLE
Add Geostream 

### PR DESCRIPTION
**Pull request by FlyingWithJerome**
@max-zilla 
The geostream module is basically finished, but the bug still exists. The lethal one is that I cannot create datapoints (probably I use it incorrectly). Sensor (Plot) level and Stream (Sensor) level are doing well.

There are also some FIXME tokens; for example, I would like to know how to represent the area of the field since the sample code used three numbers for one single point ([lat, lng, sea_lvl] ?)

The geostream function is in an individual branch, but Github still merged it with my other pull request. I hope we can merge this PR to the master ASAP as it becomes very cumbersome.

### CODE REVIEW

**Comment by FlyingWithJerome** [comment]
@czender 
The metadata for the flattened Environmental Logger is [here (with the information provided by Craig)](https://gist.github.com/FlyingWithJerome/886f6d2e02b8ecd100739a1a470a658f)

**Comment by max-zilla** [comment]
@FlyingWithJerome @czender I will review this week.

**Comment by FlyingWithJerome** [comment]
@dlebauer @max-zilla 
I would like to know what does the [extractor-meteorlogical](https://github.com/terraref/extractors-meterological) do, since it also has an instrument called "weather station (I don't know whether it is the same one in the Environmental Logger)," converts the data into netCDF format and pushes to the Geostream. Just in case if both extractors have any coincidence and establish a naming convention.

Also, seems the Level 1 data of meteorlogical extractor is not available on the ROGER?

**Comment by max-zilla** [comment]
@FlyingWithJerome that is for a different weather station, a stationary MAC Weather Station with weather/irrigation/lightning data. I plan to eventually combine these repositories - more discussion on that here: https://github.com/terraref/documentation/pull/147/files

**Comment by max-zilla** [comment]
Going to merge this - will make a few changes and make followup PR so @FlyingWithJerome can see them.

**Comment by FlyingWithJerome** [comment]
@max-zilla 
Sounds great, merge it and fix it in a new PR.

**Pull request merged**
