### PR TITLE
Add a test.sh

### PR DESCRIPTION
**Pull request by FlyingWithJerome**
Please note: [test.sh](/FlyingWithJerome/extractors-environmental/blob/test_shell/environmentlogger/test.sh) is in the [test_shell branch,](/FlyingWithJerome/extractors-environmental/tree/test_shell/environmentlogger) 

Please ignore everything except test.sh; everything else is in the [master branch](/FlyingWithJerome/extractors-environmental/tree/master/environmentlogger).

### CODE REVIEW

**Comment by FlyingWithJerome** [comment]
@czender 
Thanks. This reminds me that I should ask David on his [issue.](https://github.com/terraref/computing-pipeline/issues/76)

@dlebauer 
If I understand your idea correctly, there will be a master test.sh which runs every secondary test.sh. By "throwing errors" we (the secondary test.sh s) will return a value between 1 - 255 or write an error message to stderr?

**Comment by FlyingWithJerome** [comment]
@czender @dlebauer 
Now the success information will be flushed to STDOUT (1) and the failure information will be flushed to STDERR (2).

**Comment by dlebauer** [comment]
Jerome that sounds correct, though I am not familiar with error codes. @robkooper suggested the approach.

**Comment by dlebauer** [comment]
I think something like

```sh
if [ "$STATUS" != "OK" ]; then 
    echo "ERROR PEcAn BUILD BROKEN" >&2
    exit 1
fi
```

From https://github.com/PecanProject/pecan/blob/master/scripts/build.sh

Will do the trick

**Comment by FlyingWithJerome** [comment]
@dlebauer 
Right now the [test.sh](https://github.com/FlyingWithJerome/extractors-environmental/blob/test_shell/environmentlogger/test.sh) has the exit code (0 for success and 1 for failure). I think test.sh is ready to be merged to the master repo now.

**Pull request merged**
