### PR TITLE
Flatten the Environmental Logger Output

### PR DESCRIPTION
**Pull request by FlyingWithJerome**
The environmental logger output nc files will no longer have groups. All the groups will be rewritten as the "sensor" attributes of the variables

### CODE REVIEW

**Comment by FlyingWithJerome** [comment]
@czender Which is a better attribute name, "sensor" or "sensor_name?"

**Comment by czender** [comment]
"sensor" is a better name.

**Comment by FlyingWithJerome** [comment]
@czender 
I read the TERRA-REF spreadsheet, and I saw that we do have the exact name for these sensors:
sensor co2: GMP 343 CO2 sensor
sensor par : ??? unknown
spectrometer: Skye PRI sensor
weather station: Thies Clima lightning/irrigation/weather data

@dlebauer 
Please correct me if there's anything wrong, thanks.

**Comment by dlebauer** [comment]
@FlyingWithJerome the sensor metadata are here: https://terraref.ncsa.illinois.edu/clowder/collection/5873a6234f0cad7d81318e36

and information about the PAR sensor is here: https://github.com/terraref/sensor-metadata/blob/master/sensors/parSensor/sensor_fixed_metadata.json 

```json
"manufacturer": "www.apogeeinstruments.com",
"model": "SQ214",
```

@craig-willis should the sensor fixed meta-data point back to the documentation in Clowder (e.g. to locate pdfs, etc)? What would be the appropriate tag?

**Comment by FlyingWithJerome** [comment]
@dlebauer 
Thanks! the table above looks better now. We will hard code these information into the environmental loggers, though the documentation from Thies Clima is all German....

**Comment by dlebauer** [comment]
@craig-willis could you please check that metadata is being used as you envision (eg dynamically queried and/or referenced)?

@FlyingWithJerome could you please upload the output of ncdump -h?

**Comment by FlyingWithJerome** [comment]
@dlebauer 
Yes, the sample output of the environmental logger Level_1 data is [here](https://gist.github.com/FlyingWithJerome/41d08f660006f516814db9214200fd87). I haven't added those model and manufacturer infos, but will do pretty soon.

**Comment by czender** [comment]
@craig-willis this PR is getting unwieldy. Please review so can get this merged.

**Comment by craig-willis** [comment]
The sensor identifiers and associated datasets in Clowder are:
* co2sensor: https://terraref.ncsa.illinois.edu/clowder/api/datasets/5873a9924f0cad7d8131b648
* parSensor: https://terraref.ncsa.illinois.edu/clowder/api/datasets/5873a8ce4f0cad7d8131ad86
* priSensor: https://terraref.ncsa.illinois.edu/clowder/api/datasets/5873a9174f0cad7d8131b09a
* weatherStation: https://terraref.ncsa.illinois.edu/clowder/api/datasets/5873a9724f0cad7d8131b4d3

Each of these as a metadata.jsonld endpoint that can be used to get fixed properties (name, serial number, etc). For example:

* https://terraref.ncsa.illinois.edu/clowder/api/datasets/5873a9724f0cad7d8131b4d3/metadata.jsonld

It's not clear to me how useful this is in the context of the current PR.  At the very least, you might consider using consistent sensor identifiers (e.g., weatherStation not weather_station, parSensor, not sensor_par, etc).

**Comment by czender** [comment]
@FlyingWithJerome please rename the values of the "sensor" attribute to co2sensor, parSensor, priSensor, weatherStation as described above...

**Comment by FlyingWithJerome** [comment]
@czender @craig-willis 
The sample flattened output of the Environmental Logger output is [here](https://gist.github.com/FlyingWithJerome/886f6d2e02b8ecd100739a1a470a658f)

**Comment by czender** [comment]
The flattening looks good. Jerome and I just discussed next steps with the metadata. We'll make sure there's usable long_names in each variable. We also want to eliminate the redundancy of sensor information and perhaps add a dummy variable for each sensor that contains it instead of putting all sensor information in each variable. That would be a different PR. Will look at what weather station format first to keep consistent. @craig-willis What do you think?

**Pull request merged**
